### ISSUE TITLE
grails war fails with ClassNotFoundException using jersey

### ISSUE THREAD

**Issue by ouroborica** [budjb/grails-jaxrs#25]
running the app in dev via grails run-app works fine, but trying to do grails war (or gradle war) ends up 
with the following (removing a lot of intermediate lines of the stack trace for brevity)

I've tried specifically adding a dependency to the jersey core with no luck.  Google only seems to point me in the direction of some inconsistency of mixing groovy and java compilation, which doesn't seem to be my issue since this project doesn't have any java classes.

org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':webapp:compileGroovy'.
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)

Caused by: java.lang.ExceptionInInitializerError
    at org.gradle.api.internal.tasks.compile.ApiGroovyCompiler.execute(ApiGroovyCompiler.java:164)
    at org.gradle.api.internal.tasks.compile.ApiGroovyCompiler.execute(ApiGroovyCompiler.java:52)
    at org.gradle.api.internal.tasks.compile.daemon.CompilerDaemonServer.execute(CompilerDaemonServer.java:53)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)

Caused by: java.lang.ClassNotFoundException: com.sun.ws.rs.ext.RuntimeDelegateImpl

switching to restlet at least seems to compile though.

**Comment by ouroborica** [comment]
and of course actually trying to deploy the war with restlet ends up with 

ERROR o.s.b.SpringApplication - Application startup failed
java.lang.NullPointerException: null
    at org.restlet.ext.servlet.ServerServlet.getInitParameter(ServerServlet.java:882)
    at org.restlet.ext.servlet.ServerServlet.getComponent(ServerServlet.java:832)
    at org.restlet.ext.servlet.ServerServlet.init(ServerServlet.java:960)
    at javax.servlet.GenericServlet.init(GenericServlet.java:158)
    at javax.servlet.Servlet$init.call(Unknown Source)

**Comment by budjb** [comment]
Is this using Grails 3? Can you post the relevant bits of the build.gradle of how you're including the plugin?

**Comment by ouroborica** [comment]
It is grails 3.1.6. 

I can see if it's possible to break off some of the various gradle files.  It's a multiple module project with structured like :  
/projectdir/ (settings.gradle here which refers to each of the sub modules)
    /grails-plugin
    /grails-webapp1
    /grails-webapp2

the webapp2's being the one with the dependency on jaxrs.  

I think actually lied when I said I was running them with grails run-app, I was running them via the main class in IntelliJ

**Comment by ouroborica** [comment]
Well I think I've found out what is happening,

if you have:  
    @Produces( [MediaType.APPLICATION_JSON] )
it fails
but 
    @Produces( ["application/json"] )
succeeds

Of course the code I'm upgrading from grails 2.5 was doing the former.   

This is probably some esoteric issue with the groovy compiler and nothing can do anything about.

**Comment by budjb** [comment]
I'm wondering if this has anything to do with bad dependency resolution. The maven-publish plugin doesn't create the POM correctly, and turns `compile` dependencies into `runtime`. I've fixed this for the latest release, but I'd like to try to recreate this with the older version just to check whether this is indeed the problem.

**Comment by budjb** [comment]
I have reproduced this. I actually couldn't get the app to run at all using jersey.

It looks like the `jersey-client` library is required for this to work correctly. That class lies in that library. Adding it manually fixed the issue, and I can `war` it fine as well.

**Comment by budjb** [comment]
This should be fixed in the next release.
